In [0]:
import torch
import numpy as np
torch.manual_seed(1234)

##Tensors
#####- scalar is single number
#####- vector is a 2D array of numbers
#####- Tensors are N-D arrays of numbers

In [0]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))

In [0]:
describe(torch.Tensor(3, 3))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[2.3759e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.6985e+22, 2.7179e+23, 2.1237e+20]])


In [0]:
describe(torch.randn(5, 3))

Type: torch.FloatTensor
Shape/size: torch.Size([5, 3])
Values: 
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036],
        [ 0.2310,  0.6931, -0.2669],
        [ 2.1785,  0.1021, -0.2590],
        [-0.1549, -1.3706, -0.1319]])


In [0]:
x = torch.arange(6).view(2,3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [0]:
x = torch.arange(0, 8)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [0]:
x = torch.arange(0, 20)

print(x.view(1, 20))
print(x.view(2, 10))
print(x.view(4, 5))
print(x.view(5, 4))
print(x.view(10, 2))
print(x.view(20, 1))

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]])


In [0]:
x = torch.arange(12).view(3, 4)
print(x.shape)

x = x.unsqueeze(dim=1)
print(x.shape)

x = x.squeeze()
print(x.shape)

torch.Size([3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4])


In [0]:
print(torch.cuda.is_available())

False
